theme: jekyll-theme-primer
title: joools.xyz wiki
url: "https://joools.xyz/"
baseurl: "/wiki/"
plugins:
  - jekyll-sitemap
markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
